apiVersion: v1
name: kindergarten # This value was modified by the initial-setup python script
description: A Helm chart for deploying kindergarten-frontend. # This value was modified by the initial-setup python script
version: 1.0
