appName: kindergarten-backend # This value was modified by the initial-setup python script

deployment:
  image:
    repository: aza67/kindergarten-backend # This value was modified by the initial-setup python script