appName: aatt2-backend # This value was modified by the initial-setup python script

deployment:
  image:
    repository: aza67/aatt2-backend # This value was modified by the initial-setup python script